service: dictService

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.getDictionaryWords
    events:
      - http:
          path: dict
          method: get
          cors: true
